# Generated by Django 5.1.6 on 2025-02-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quiz_cateogry_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='cateogry_featured',
            new_name='category_featured',
        ),
    ]
