# Generated by Django 5.1.6 on 2025-02-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_rename_ansewer_text_question_correct_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_options',
            field=models.JSONField(default=list, null=True),
        ),
    ]
